version: "3.6"

volumes:
  glconf:
    driver: nfs
    driver_opts:
      share: "{{ DK_REPO_NFS_HOST }}:{{ DK_REPO_NFS_PATH }}/glconf"
  gllog:
    driver: nfs
    driver_opts:
      share: "{{ DK_REPO_NFS_HOST }}:{{ DK_REPO_NFS_PATH }}/gllog"
  gldata:
    driver: nfs
    driver_opts:
      share: "{{ DK_REPO_NFS_HOST }}:{{ DK_REPO_NFS_PATH }}/gldata"
  glr1conf:
    driver: nfs
    driver_opts:
      share: "{{ DK_REPO_NFS_HOST }}:{{ DK_REPO_NFS_PATH }}/glr1conf"
  didata:
    driver: nfs
    driver_opts:
      share: "{{ DK_REPO_NFS_HOST }}:{{ DK_REPO_NFS_PATH }}/didata"

services:
  web:
    image: "gitlab/gitlab-ce:10.8.7-ce.0"
    volumes:
      - glconf:/etc/gitlab
      - gllog:/var/log/gitlab
      - gldata:/var/opt/gitlab
    hostname: '{{ DK_REPO_HOST }}'
    shm_size: '256m'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://{{ DK_REPO_HOST }}:8000'
        gitlab_rails['gitlab_shell_ssh_port'] = 2200
    ports:
      - "8000:8000"
      - "2200:22"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s

  runner-1:
    image: "gitlab/gitlab-runner:v10.8.2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - glr1conf:/etc/gitlab-runner
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s

  di:
    image: "registry:2.8.1"
    volumes:
      - didata:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 60s
